const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
// const _ = require("lodash");

const app = express();
app.use(bodyParser.json());
app.use(cors());

let notes = [
	{
		id: 0,
		title: "Google I/O",
		content:
			"Google I/O is back May 18-20, online, and free for everyone. Join us live., I/O is live keynotes, hands-on learning with Google experts, and a first look at the latest developer products., Make sure to check back for more updates!",
		linkURL: "g.co/io",
		linkText: "Google I/O keynote",
		color: "blue",
		image: "",
		list: "",
		archive: false,
		trash: false,
	},
	{
		id: 1,
		title: "SVG illustrations",
		content: "Free SVGs illustrations for lot of purposes",
		linkURL: "undraw.co",
		linkText: "",
		color: "purple",
		image: "",
		list: "Work",
		archive: false,
		trash: false,
	},
	{
		id: 2,
		title: "Ian and Paul",
		content: "",
		linkURL: "https://www.youtube.com/watch?v=X1dOxpTUjHs",
		linkText: "",
		color: "orange",
		image: "",
		list: "Fun",
		archive: false,
		trash: false,
	},
	{
		id: 3,
		title: "Damon",
		content:
			"If your are gonna be bad, be bad with purpose. Otherwise you're not just forgiving.",
		linkURL: "https://www.netflix.com/in/title/70143860",
		linkText: "The Vampire Diaries",
		color: "blue",
		image: "",
		list: "Shows",
		archive: false,
		trash: false,
	},
	{
		id: 4,
		title: "Loops",
		content:
			"How to keep a programmer in the shower forever., Show him the shampoo bottle instructions: Lather. Rinse. Repeat.",
		linkURL: "",
		linkText: "",
		color: "",
		image: "",
		list: "Jokes",
		archive: true,
		trash: false,
	},
	{
		id: 5,
		title: "Eva",
		content:
			"Isn't it funny ? The people who we despise the most are the people who are most like us",
		linkURL: "https://www.netflix.com/in/title/80100172",
		linkText: "Dark | Netflix",
		color: "red",
		image: "",
		list: "Shows",
		archive: false,
		trash: false,
	},
	{
		id: 6,
		title: "",
		content: "The Old Astronomer to His Pupil",
		linkURL: "https://www.naic.edu/~gibson/poems/swilliams1.html",
		linkText: "",
		color: "indigo",
		image: "",
		list: "Work",
		archive: false,
		trash: false,
	},
	{
		id: 7,
		title: "Rise of Flutter",
		content:
			"Is flutter going to kill Native Android?,It already is known fact, flutter can be used for cross platform app development,Meanwhile Google has came up with the solution of independence from JVMs.",
		linkURL: "https://www.instagram.com/p/CUB3uVNFczN/",
		linkText: "The Flutter Way",
		color: "pink",
		image: "",
		list: "Work",
		archive: true,
		trash: false,
	},
	{
		id: 8,
		title: "Modern Portfolio",
		content:
			"I finished a simple HTML + CSS (SASS) project: Modern Portfolio.,It was a simple project series at Brad Traversery on youtube.,Might delete later",
		linkURL: "https://akshatmittal61.github.io/modern_portfolio",
		linkText: "",
		color: "orange",
		image: "",
		list: "Work",
		archive: false,
		trash: true,
	},
];
let lists = [];
let archives = [];
let trash = [];
const updateLists = () => {
	let allLists = [];
	notes.map((note) => {
		allLists = note.list === "" ? [...allLists] : [...allLists, note.list];
	});
	lists = [...new Set(allLists)];
};
const updateArchives = () => {
	let allArchives = [];
	notes.map((note) => {
		allArchives = note.archive ? [...allArchives, note] : [...allArchives];
	});
	archives = [...new Set(allArchives)];
};
const updateBin = () => {
	let allTrash = [];
	notes.map((note) => {
		allTrash = note.trash ? [...allTrash, note] : [...allTrash];
	});
	trash = [...new Set(allTrash)];
};
updateLists();
updateArchives();
updateBin();
const images = [
	"3Px Tile",
	"45 Degree Fabric (Dark)",
	"45 Degree Fabric (Light)",
	"60º lines",
	"Absurdity",
	"AG Square",
	"Always Grey",
	"Arabesque",
	"Arches",
	"Argyle",
	"Asfalt (Dark)",
	"Asfalt (Light)",
	"Assault",
	"Axiom Pattern",
	"Az Subtle",
	"Back Pattern",
	"Basketball",
	"Batthern",
	"Bedge Grunge",
	"Beige Paper",
	"Billie Holiday",
	"Binding Dark",
	"Binding Light",
	"Black Felt",
	"Black Linen",
	"Black Linen 2",
	"Black Mamba",
	"Black Orchid",
	"Black Paper",
	"Black Scales",
	"Black Thread",
	"Black Thread (Light)",
	"Black Twill",
	"Blizzard",
	"Blu Stripes",
	"Bo Play",
	"Brick Wall",
	"Brick Wall (Dark)",
	"Bright Squares",
	"Brilliant",
	"Broken Noise",
	"Brushed Alum",
	"Brushed Alum Dark",
	"Buried",
	"Candyhole",
	"Carbon Fibre",
	"Carbon Fibre Big",
	"Carbon Fibre V2",
	"Cardboard",
	"Cardboard Flat",
	"Cartographer",
	"Checkered Light Emboss",
	"Checkered Pattern",
	"Church",
	"Circles",
	"Classy Fabric",
	"Clean Gray Paper",
	"Clean Textile",
	"Climpek",
	"Cloth Alike",
	"Concrete Wall",
	"Concrete Wall 2",
	"Concrete Wall 3",
	"Connected",
	"Corrugation",
	"Cream Dust",
	"Cream Paper",
	"Cream Pixels",
	"Crisp Paper Ruffles",
	"Crissxcross",
	"Cross Scratches",
	"Cross Stripes",
	"Crossword",
	"Cubes",
	"Cutcube",
	"Dark Brick Wall",
	"Dark Circles",
	"Dark Denim",
	"Dark Denim 3",
	"Dark Dot",
	"Dark Dotted 2",
	"Dark Exa",
	"Dark Fish Skin",
	"Dark Geometric",
	"Dark Leather",
	"Dark Matter",
	"Dark Mosaic",
	"Dark Stripes",
	"Dark Stripes (Light)",
	"Dark Tire",
	"Dark Wall",
	"Dark Wood",
	"Darth Stripe",
	"Debut Dark",
	"Debut Light",
	"Diagmonds (Dark)",
	"Diagmonds (Light)",
	"Diagonal Noise",
	"Diagonal Striped Brick",
	"Diagonal Waves",
	"Diagonales Decalees",
	"Diamond Eyes",
	"Diamond Upholstery",
	"Diamonds Are Forever",
	"Dimension",
	"Dirty Old Black Shirt",
	"Dotnoise Light Grey",
	"Double Lined",
	"Dust",
	"Ecailles",
	"Egg Shell",
	"Elastoplast",
	"Elegant Grid",
	"Embossed Paper",
	"Escheresque",
	"Escheresque Dark",
	"Exclusive Paper",
	"Fabric (Plaid)",
	"Fabric 1 (Dark)",
	"Fabric 1 (Light)",
	"Fabric Of Squares",
	"Fake Brick",
	"Fake Luxury",
	"Fancy Deboss",
	"Farmer",
	"Felt",
	"First Aid Kit",
	"Flower Trail",
	"Flowers",
	"Foggy Birds",
	"Food",
	"Football (No Yardlines)",
	"French Stucco",
	"Fresh Snow",
	"Gold Scale",
	"Gplay",
	"Gradient Squares",
	"Graphcoders Lil Fiber",
	"Graphy (Dark)",
	"Graphy (Light)",
	"Gravel",
	"Gray Floral",
	"Gray Lines",
	"Gray Sand",
	"Green Cup",
	"Green Dust and Scratches",
	"Green Fibers",
	"Green Gobbler",
	"Grey Jean",
	"Grey Sandbag",
	"Grey Washed Wall",
	"Greyzz",
	"Grid",
	"Grid Me",
	"Grid Noise",
	"Grilled Noise",
	"Groovepaper",
	"Grunge Wall",
	"Gun Metal",
	"Handmade Paper",
	"Hexabump",
	"Hexellence",
	"Hixs Evolution",
	"Hoffman",
	"Honey I'm Subtle",
	"Ice Age",
	"Inflicted",
	"Inspiration Geometry",
	"Iron Grip",
	"Kinda Jean",
	"Knitted Netting",
	"Knitted Sweater",
	"Kuji",
	"Large Leather",
	"Leather",
	"Light Aluminum",
	"Light Gray",
	"Light Grey Floral Motif",
	"Light Honeycomb",
	"Light Honeycomb (Dark)",
	"Light Mesh",
	"Light Paper Fibers",
	"Light Sketch",
	"Light Toast",
	"Light Wool",
	"Lined Paper",
	"Lined Paper 2",
	"Little Knobs",
	"Little Pluses",
	"Little Triangles",
	"Low Contrast Linen",
	"Lyonnette",
	"Maze Black",
	"Maze White",
	"Mbossed",
	"Medic Packaging Foil",
	"Merely Cubed",
	"Micro Carbon",
	"Mirrored Squares",
	"Mocha Grunge",
	"Mooning",
	"Moulin",
	"My Little Plaid (Dark)",
	"My Little Plaid (Light)",
	"Nami",
	"Nasty Fabric",
	"Natural Paper",
	"Navy",
	"Nice Snow",
	"Nistri",
	"Noise Lines",
	"Noise Pattern With Subtle Cross Lines",
	"Noisy",
	"Noisy Grid",
	"Noisy Net",
	"Norwegian Rose",
	"Notebook",
	"Notebook (Dark)",
	"Office",
	"Old Husks",
	"Old Map",
	"Old Mathematics",
	"Old Moon",
	"Old Wall",
	"Otis Redding",
	"Outlets",
	"P1",
	"P2",
	"P4",
	"P5",
	"P6",
	"Padded",
	"Padded (Light)",
	"Paper",
	"Paper 1",
	"Paper 2",
	"Paper 3",
	"Paper Fibers",
	"Paven",
	"Perforated White Leather",
	"Pineapple Cut",
	"Pinstripe (Dark)",
	"Pinstripe (Light)",
	"Pinstriped Suit",
	"Pixel Weave",
	"Polaroid",
	"Polonez Pattern",
	"Polyester Lite",
	"Pool Table",
	"Project Paper",
	"Ps Neutral",
	"Psychedelic",
	"Purty Wood",
	"Pw Pattern",
	"Pyramid",
	"Quilt",
	"Random Grey Variations",
	"Ravenna",
	"Real Carbon Fibre",
	"Rebel",
	"Redox 01",
	"Redox 02",
	"Reticular Tissue",
	"Retina Dust",
	"Retina Wood",
	"Retro Intro",
	"Rice Paper",
	"Rice Paper #2",
	"Rice Paper #3",
	"Robots",
	"Rocky Wall",
	"Rough Cloth",
	"Rough Cloth (Light)",
	"Rough Diagonal",
	"Rubber Grip",
	"Sandpaper",
	"Satin Weave",
	"Scribble Light",
	"Shattered",
	"Shattered (Dark)",
	"Shine Caro",
	"Shine Dotted",
	"Shley Tree 1",
	"Shley Tree 2",
	"Silver Scales",
	"Simple Dashed",
	"Simple Horizontal Light",
	"Skeletal Weave",
	"Skewed Print",
	"Skin Side Up",
	"Skulls",
	"Slash It",
	"Small Crackle Bright",
	"Small Crosses",
	"Smooth Wall (Dark)",
	"Smooth Wall (Light)",
	"Sneaker Mesh Fabric",
	"Snow",
	"Soft Circle Scales",
	"Soft Kill",
	"Soft Pad",
	"Soft Wallpaper",
	"Solid",
	"Sos",
	"Sprinkles",
	"Squairy",
	"Squared Metal",
	"Squares",
	"Stacked Circles",
	"Stardust",
	"Starring",
	"Stitched Wool",
	"Strange Bullseyes",
	"Straws",
	"Stressed Linen",
	"Stucco",
	"Subtle Carbon",
	"Subtle Dark Vertical",
	"Subtle Dots",
	"Subtle Freckles",
	"Subtle Grey",
	"Subtle Grunge",
	"Subtle Stripes",
	"Subtle Surface",
	"Subtle White Feathers",
	"Subtle Zebra 3D",
	"Subtlenet",
	"Swirl",
	"Tactile Noise (Dark)",
	"Tactile Noise (Light)",
	"Tapestry",
	"Tasky",
	"Tex2Res1",
	"Tex2Res2",
	"Tex2Res3",
	"Tex2Res4",
	"Tex2Res5",
	"Textured Paper",
	"Textured Stripes",
	"Texturetastic Gray",
	"Ticks",
	"Tileable Wood",
	"Tileable Wood (Colored)",
	"Tiny Grid",
	"Translucent Fibres",
	"Transparent Square Tiles",
	"Tree Bark",
	"Triangles",
	"Triangles 2",
	"Triangular",
	"Tweed",
	"Twinkle Twinkle",
	"Txture",
	"Type",
	"Use Your Illusion",
	"Vaio",
	"Vertical Cloth",
	"Vichy",
	"Vintage Speckles",
	"Wall #4 Light",
	"Washi",
	"Wave Grid",
	"Wavecut",
	"Weave",
	"Wet Snow",
	"White Bed Sheet",
	"White Brick Wall",
	"White Brushed",
	"White Carbon",
	"White Carbonfiber",
	"White Diamond",
	"White Diamond (Dark)",
	"White Leather",
	"White Linen",
	"White Paperboard",
	"White Plaster",
	"White Sand",
	"White Texture",
	"White Tiles",
	"White Wall",
	"White Wall 2",
	"White Wall 3",
	"White Wall 3[2]",
	"White Wave",
	"Whitey",
	"Wide Rectangles",
	"Wild Flowers",
	"Wild Oliva",
	"Wine Cork",
	"Wood",
	"Wood Pattern",
	"Worn Dots",
	"Woven",
	"Woven (Light)",
	"Xv",
	"Zig Zag",
	"Вlack Lozenge",
];

app.get("/", (req, res) => {
	console.log(lists);
	updateLists();
	updateArchives();
	updateBin();
	res.send(notes);
});
app.get("/api/notes", (req, res) => {
	res.send(notes);
});
app.get("/api/lists", (req, res) => {
	res.send(lists);
});
app.get("/api/archives", (req, res) => {
	res.send(archives);
});
app.get("/api/bin", (req, res) => {
	res.send(trash);
});
app.post("/api/new", (req, res) => {
	const newNote = { id: notes.length, ...req.body };
	console.log(newNote);
	notes = [...notes, newNote];
	updateLists();
	updateArchives();
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server started at port ${PORT}`));
